export interface Vendedor {
    vendc_icod_vendedor: number,
    vendc_iid_vendedor: string | null,
    vendc_vnombre_vendedor: string | null,
    vendc_vdireccion: string | null,
    vendc_vnumero_telefono: string | null,
    vendc_cnumero_dni: string | null,
    tablc_iid_situacion_vendedor: number | null,
    vendc_vpassword_vendedor: string | null,
    vendc_iusuario_crea: number | null,
    vendc_sfecha_crea: string | null,
    vendc_vpc_crea: string | null,
    vendc_iusuario_modifica: number | null,
    vendc_sfecha_modifica: string | null,
    vendc_vpc_modifica: string | null,
    vendc_iusuario_elimina: number | null,
    vendc_sfecha_elimina: string | null,
    vendc_vpc_elimina: string | null,
    vendc_flag_estado: boolean | null,
    vendc_tipo_vendedor: number | null,
    vendc_icod_pvt: number | null,
    vendc_vcorreo: string | null,
    zonc_icod_zona: number | null,
    vendc_vcod_vendedor: string | null,
}